Combine multiple trace tests into single file
informalsystems/atomkraft pull request #175
Opened 2022-10-28 08:51 UTC by hvanz

Closes #168

2022-11-02 11:02 UTC, rnbguy requested changes
Thanks for the PR. I added some suggestions.

I noticed, this is only for `test trace`. `test model` still generates multiple test files. Do you think it would make sense to include that in this PR as well?

2022-11-02 11:02 UTC, rnbguy commented on atomkraft/utils/filesystem.py
> +    return path.replace("/", "_").replace(".", "_").replace(":", "_").replace("-", "_")
Can we use [`case-converter`](https://pypi.org/project/case-converter) instead?

2022-11-02 11:02 UTC, rnbguy commented on atomkraft/utils/helpers.py
> +def natural_sort(key):
Please annotate with type `pathlib.Path`.

2022-11-02 11:02 UTC, rnbguy commented on atomkraft/utils/helpers.py
> +    return [int(s) if s.isdigit() else s.lower() for s in re.split("(\\d+)", str(key))]
~I am confused by `str(key)` here. Can you give me an example of non-`str` key for this method?~

This is a method to compute keys for a sort. Does it make sense to rename the method to `natural_key`?

2022-11-02 11:02 UTC, rnbguy commented on atomkraft/test/model.py
> +    test_group = rename_chars(f"{model.stem}_{timestamp}")
thanks for creating the util method for this! :+1:

2022-11-04 08:54 UTC, hvanz commented on atomkraft/utils/filesystem.py
> +    return path.replace("/", "_").replace(".", "_").replace(":", "_").replace("-", "_")
Done.

2022-11-11 10:57 UTC, hvanz commented
> I noticed, this is only for `test trace`. `test model` still generates multiple test files. Do you think it would make sense to include that in this PR as well?

@rnbguy I included this change you suggested in this PR, together with a refactoring of all the testing functionality in a single `Test` class

2022-11-11 12:51 UTC, rnbguy commented on atomkraft/test/test.py
> +class Test:
Great that you used a class for this.

2022-11-11 12:51 UTC, rnbguy commented on atomkraft/utils/filesystem.py
> +def copy_if_exists(srcs: Union[Path, List[Path]], dst_path: Path):
Thanks for putting this here.

2022-11-11 12:51 UTC, rnbguy approved these changes
Awesome ! Thanks for this PR.

2022-11-11 16:38 UTC, merged