imp: add bech32 address support for Ethermint chains
informalsystems/atomkraft pull request #212
Opened 2023-03-31 20:21 UTC by GAtom22

## Description

This PR introduces the changes needed to make the proper bech32 address encoding to be able to use Atomkraft with Ethermint chains

Closes https://github.com/informalsystems/atomkraft/issues/211

2023-04-04 11:45 UTC, rnbguy requested changes
Many thanks for this PR. I requested some changes. Once resolved, I will merge it.

2023-04-04 11:45 UTC, rnbguy commented on atomkraft/chain/node.py
> +        coin = supported_coins.setdefault(self.coin_type)
why do you call `.setdefault()`? isn't `.get()` enough?

2023-04-04 11:45 UTC, rnbguy commented on atomkraft/chain/node.py
> +        self.wallet = hdwallet.BIP44HDWallet(cryptocurrency=coin).from_entropy(
I can't allow this change, as Cosmos community uses coin types others than 118.

Example,

| SLIP44 | Symbol | Chain         |
|--------|--------|---------------|
| 529    | SCRT   | Secret Network|
| 394    | CRO    | Crypto Chain  |
| 330    | LUNA   | Terra         |
| 852    | DSM    | Desmos        |

2023-04-04 11:45 UTC, rnbguy commented on atomkraft/chain/node.py
> +        self.wallet = hdwallet.BIP44HDWallet(cryptocurrency=coin).from_entropy(
maybe, add a logic, when coin is None, it falls back to `LocalCC`.

2023-04-04 11:45 UTC, rnbguy commented on atomkraft/chain/node.py
> +                return bip_utils.Bech32Encoder.Encode(prefix, bytes.fromhex(self.wallet.address()[2:]))
I know this is correct, as I just tested it with `evmosd key parse`. But can you provide an official reference for this?

2023-04-05 21:40 UTC, GAtom22 commented on atomkraft/chain/node.py
> +                return bip_utils.Bech32Encoder.Encode(prefix, bytes.fromhex(self.wallet.address()[2:]))
By using the address bytes for address encoding, we can convert addresses between hex and bech32 easily. See [this cmd](https://github.com/evmos/ethermint/blob/2814c7857f1cdbb35cdad21bf3bc160a6b29021b/client/debug/debug.go#L83-L116) that is used for this purpose

2023-04-06 10:35 UTC, rnbguy approved these changes
LGTM :+1:

2023-04-06 10:35 UTC, merged

2023-04-06 10:36 UTC, rnbguy commented
Thanks @GAtom22 :pray: